server {
    listen 80;
    listen [::]:80;
    server_name shizusu.cc.cd;

    root /var/www/shizusu;
    index index.html;

    access_log /var/log/nginx/shizusu.access.log;
    error_log /var/log/nginx/shizusu.error.log;

    location = /download {
        proxy_pass http://127.0.0.1:8088;
        proxy_set_header Host $host;
    }
    location = /download.html {
        proxy_pass http://127.0.0.1:8088;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
